FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY app.py .

RUN useradd -u 1001 -r -g 0 -m appuser && \
    chown -R 1001:0 /app && chmod -R g+rw /app
USER 1001

ENV PYTHONUNBUFFERED=1
ENV MICROSERVICE_A_URL="http://microservice-a:8080"
ENV REQUEST_RATE=2.0
ENV PRIME_N=30000

CMD ["python", "-u", "app.py"]
