{{- if .Values.ranFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hub.fullname" . }}-ran-frontend
  labels:
    {{- include "hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: ran-frontend
spec:
  replicas: {{ .Values.ranFrontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "hub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ran-frontend
  template:
    metadata:
      labels:
        {{- include "hub.labels" . | nindent 8 }}
        app.kubernetes.io/component: ran-frontend
    spec:
      containers:
        - name: ran-frontend
          image: "{{ .Values.image.registry }}/{{ .Values.image.ranFrontend }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.ranFrontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ranFrontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ranFrontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub.fullname" . }}-ran-frontend
  labels:
    {{- include "hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: ran-frontend
spec:
  type: {{ .Values.ranFrontend.service.type }}
  ports:
    - port: {{ .Values.ranFrontend.service.port }}
      targetPort: {{ .Values.ranFrontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ran-frontend
{{- if .Values.global.routes.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "hub.fullname" . }}-ran-frontend
  labels:
    {{- include "hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: ran-frontend
spec:
  to:
    kind: Service
    name: {{ include "hub.fullname" . }}-ran-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
{{- end }}
