{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.rbac.serviceAccount.name }}
  namespace: {{ include "lokistack.namespace" . }}
{{- end }}
